import Mathlib.GroupTheory.Congruence.Basic
import Mathlib.Data.Multiset.Basic
import Mathlib.Tactic.FinCases
import F1.F1moduleCat

/-! The functor to F1Module to AddCommMonCat. -/

universe u

open CategoryTheory

namespace F1module

variable (M : Type u) [F1module M]

/-- `{c} ~ {x 0} + ⋯ + {x (n-1)}` whenever `c ∈ hadd n x`, for every `n`. -/
inductive envRel : Multiset M → Multiset M → Prop
  | of_mem {n : ℕ} (x : Fin n → M) {c : M} (h : c ∈ hadd n x) :
      envRel {c} (∑ i, ({x i} : Multiset M))

def envCon : AddCon (Multiset M) := addConGen (envRel M)

/-- The enveloping commutative monoid of an `F1module`. -/
abbrev Env : Type u := (envCon M).Quotient

def ι (m : M) : Env M := (envCon M).mk' {m}

theorem ι_of_mem {n : ℕ} (x : Fin n → M) {c : M} (h : c ∈ hadd n x) :
    ι M c = ∑ i, ι M (x i) := by
  simp only [ι, ← map_sum]
  refine (AddCon.eq _).2 ?_
  tauto

/-- The unit `M → F (Env M)`. -/
def unit : F1module.Hom M (Env M) where
  toFun := ι M
  map_hadd n x := by
    rintro _ ⟨c, hc, rfl⟩
    rw [AddMonoid.hadd_eq_sum]; exact ι_of_mem M x hc
  map_zero' := by
    have := ι_of_mem (M:=M) (fun x ↦ zero) (F1module.zero_mem 0)
    exact ((fun a ↦ this) ∘ fun a ↦ M) M

@[simp]
theorem unit_apply (m : M) : unit M m = ι M m := rfl


/-! ### Arities `≤ 2` suffice

The congruence `envCon M` is already generated by the relations of arity `0`, `1`, `2`.
Proof by (strong) induction on `n`: for `n > 2` split `Fin n` into the blocks
`P₀ = {n-1}ᶜ` and `P₁ = {n-1}`, regroup with `hadd_assoc`, and chain
`{c} ≈ {e} + {e'}` (arity 2) with the induction hypothesis on each block. -/

/-- The relations of `envRel` of arity at most `2`. -/
inductive envRel₂ : Multiset M → Multiset M → Prop
  | of_mem {n : ℕ} (hn : n ≤ 2) (x : Fin n → M) {c : M} (h : c ∈ hadd n x) :
      envRel₂ {c} (∑ i, ({x i} : Multiset M))



/-- Every relation of `envRel` holds in the congruence generated by `envRel₂`. -/
theorem envRel_le_addConGen_envRel₂ (n : ℕ) :
    ∀ (x : Fin n → M) (c : M), c ∈ hadd n x →
      addConGen (envRel₂ M) {c} (∑ i, ({x i} : Multiset M)) := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  intro x c hc
  -- `n = 0, 1, 2`: by hypothesis
  by_cases hn : n ≤ 2
  · exact AddConGen.Rel.of _ _ (envRel₂.of_mem hn x hc)
  push Not at hn
  -- the partition `P₀ = {n-1}ᶜ`, `P₁ = {n-1}`
  let l : Fin n := ⟨n - 1, by omega⟩
  let p : partition n 2 :=
    { toFun := ![({l}ᶜ : Finset (Fin n)), {l}]
      isPar := fun i => by
        by_cases h : i = l
        · refine ⟨1, by simp [h], fun j hj => ?_⟩
          fin_cases j <;> simp_all
        · refine ⟨0, by simp [h], fun j hj => ?_⟩
          fin_cases j <;> simp_all }
  -- regroup `c` along `p`
  have hc' : c ∈ HyperAdd.set M n (fun i => ({x i} : Set M)) :=
    Set.mem_iUnion.2 ⟨fun i => ⟨x i, rfl⟩, hc⟩
  obtain ⟨b, hb⟩ := Set.mem_iUnion.1 (F1module.hadd_assoc p _ hc')
  -- `e = b 0`, `e' = b 1`: `{b j} ≈ ∑_{i ∈ P_j} {x i}` by the induction hypothesis
  have key : ∀ j : Fin 2,
      addConGen (envRel₂ M) {(b j : M)} (∑ i ∈ p.toFun j, ({x i} : Multiset M)) := by
    intro j
    obtain ⟨a, ha⟩ := Set.mem_iUnion.1 (b j).2
    have hax : ∀ i, (a i : M) = x i := fun i => Set.mem_singleton_iff.1 (a i).2
    simp only [hax] at ha
    have hlt : (p.toFun j).card < n := by
      fin_cases j
      · change ({l}ᶜ : Finset (Fin n)).card < n
        rw [Finset.card_compl, Finset.card_singleton, Fintype.card_fin]; omega
      · change ({l} : Finset (Fin n)).card < n
        rw [Finset.card_singleton]; omega
    have hsum : ∑ i ∈ p.toFun j, ({x i} : Multiset M)
        = ∑ k, ({x ((p.toFun j).orderIsoOfFin rfl k)} : Multiset M) := by
      rw [← Finset.sum_coe_sort]
      exact (Equiv.sum_comp ((p.toFun j).orderIsoOfFin rfl).toEquiv
        (fun i => ({x i} : Multiset M))).symm
    rw [hsum]
    exact ih _ hlt _ _ ha
  -- `{c} ≈ {e} + {e'}` by arity 2
  have h2 : addConGen (envRel₂ M) {c} (∑ j : Fin 2, ({(b j : M)} : Multiset M)) :=
    AddConGen.Rel.of _ _ (envRel₂.of_mem le_rfl _ hb)
  rw [Fin.sum_univ_two] at h2
  -- `∑_{i < n} {x i} = ∑_{i ∈ P₀} {x i} + ∑_{i ∈ P₁} {x i}`
  have hsplit : ∑ i, ({x i} : Multiset M)
      = ∑ i ∈ p.toFun 0, ({x i} : Multiset M) + ∑ i ∈ p.toFun 1, ({x i} : Multiset M) :=
    (Finset.sum_compl_add_sum {l} _).symm
  rw [hsplit]
  exact (addConGen (envRel₂ M)).trans h2 ((addConGen (envRel₂ M)).add (key 0) (key 1))

/-- `envCon M` is generated by the relations of arity `≤ 2`. -/
theorem addConGen_envRel₂ : addConGen (envRel₂ M) = envCon M := by
  apply le_antisymm
  · rw [AddCon.addConGen_le]
    intro a b h
    cases h with
    | of_mem _ x hc => exact AddConGen.Rel.of _ _ (envRel.of_mem x hc)
  · rw [envCon, AddCon.addConGen_le]
    intro a b h
    cases h with
    | of_mem x hc => exact envRel_le_addConGen_envRel₂ M _ x _ hc


variable {M} {A : Type u} [AddCommMonoid A]

/-- Universal property: a morphism `M → F A` factors uniquely through `Env M`. -/
def lift (φ : F1module.Hom M A) : Env M →+ A :=
  (envCon M).lift (Multiset.sumAddMonoidHom.comp (Multiset.mapAddMonoidHom φ)) <|
    by
      rw [envCon,AddCon.addConGen_le]
      intro A B h
      obtain ⟨x, hc⟩ := h
      have := φ.mem_hadd_of_mem_hadd _ x hc
      rw [AddMonoid.hadd_eq_sum] at this
      simpa [map_sum] using this

@[simp] theorem lift_ι (φ : F1module.Hom M A) (m : M) : lift φ (ι M m) = φ m := by
  simp [lift, ι]

theorem hom_ext {f g : Env M →+ A} (h : ∀ m, f (ι M m) = g (ι M m)) : f = g :=
  AddCon.hom_ext <| Multiset.addHom_ext h   -- singletons generate `Multiset M`

end F1module

namespace F1moduleCat

/-- **The enveloping monoid functor**, defined by hand: `M ↦ Env M`, and a morphism
`g : M ⟶ N` goes to the unique additive map `Env M → Env N` with `ι m ↦ ι (g m)`. -/
def env : F1moduleCat.{u} ⥤ AddCommMonCat.{u} where
  obj M := AddCommMonCat.of (F1module.Env M)
  map {_ N} g := AddCommMonCat.ofHom (F1module.lift ((F1module.unit N).comp g.hom))
  map_id M := by
    apply AddCommMonCat.hom_ext
    apply F1module.hom_ext
    intro m
    trivial
  map_comp {M N P} f g := by
    apply AddCommMonCat.hom_ext
    apply F1module.hom_ext
    intro m
    trivial

@[simp] theorem env_obj (M : F1moduleCat.{u}) :
    env.obj M = AddCommMonCat.of (F1module.Env M) := rfl

@[simp] theorem env_map_ι {M N : F1moduleCat.{u}} (g : M ⟶ N) (m : M) :
    (env.map g).hom (F1module.ι M m) = F1module.ι N (g.hom m) := by
  trivial

/-- `env ⊣ AddCommMonCat.toF1moduleCat`: maps `Env M → A` of monoids are the same as
morphisms `M → A` of `F1module`s. -/
def envAdj : env.{u} ⊣ AddCommMonCat.toF1moduleCat.{u} :=
  Adjunction.mkOfHomEquiv
    { homEquiv := fun M A =>
        { toFun := fun f => F1moduleCat.ofHom (f.hom.toF1moduleHom.comp (F1module.unit M))
          invFun := fun φ => AddCommMonCat.ofHom (F1module.lift φ.hom)
          left_inv := fun f => by
            apply AddCommMonCat.hom_ext
            apply F1module.hom_ext
            intro m
            -- goal: lift (f ∘ ι) (ι m) = f (ι m)
            exact F1module.lift_ι _ m
          right_inv := fun φ => by
            ext m
            -- goal: (lift φ) (ι m) = φ m
            exact F1module.lift_ι φ.hom m (A:=A)}
      homEquiv_naturality_left_symm := fun f g => by
        apply AddCommMonCat.hom_ext
        apply F1module.hom_ext
        intro m
        trivial
      homEquiv_naturality_right := fun f g => by
        ext m
        rfl }

end F1moduleCat
